### ISSUE TITLE
In index.html for banana simultor

### ISSUE THREAD

**Issue by CAProductions** [pikapower9080/pikapower9080.github.io#4]
Change this:
<h2 class="changelogtitle">Banana Simulator v0.5.0</h2>  <h2>Beta!!!</h2>
        <p>Banana simulator is eary in development and many bugs may occour.<br> Your save may also be reset occasionally. Have fun!</p>
        <div id="changelog_content">
to this:
<h2 class="changelogtitle">Banana Simulator v0.5.0</h2>  <h2>Beta!!!</h2>
        <p>Banana simulator is early in development and many bugs may occour.<br> Your save may also be reset occasionally. Have fun!</p>
        <div id="changelog_content">
----------------------------------
yes I only changed one letter fix now or I will be super sad

**Comment by bleov** [comment]
wait what did you change 😳 i am blind ❌ 👁️

**Comment by bleov** [comment]
oh ok change on the way 👍🏻

**Comment by bleov** [comment]
Fixed!!! Thank you! 🙂
